# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Seb's repository
tagline:          
description:      'Random thoughts and bits of codes compiled along the way'
url:              https://e5k.github.io
baseurl:          

author:           
  name:           'Sébastien Biass'
  url:            https://e5k.github.io

# Custom vars
version:          

github:           
  repo:           https://github.com/e5k

paginate: 5
plugins: 	 				[jekyll-paginate]
paginate_path: 		'/page:num/'
