# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Seb's repository
tagline:          
description:      'Random thoughts and bits of codes compiled along the way'
url:              https://e5k.github.io
baseurl:          

author:           
  name:           'Sébastien Biass'
  url:            https://e5k.github.io

# Custom vars
version:          

github:           
  repo:           https://github.com/e5k
  
markdown: kramdown
kramdown:
  input: GFM          # this is a support for GitHub Flavored Markdown

paginate: 20
plugins: 	 				
  - jekyll-paginate
  - jekyll-seo-tag
paginate_path: 		'/page:num/'
